# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import session_pb2 as session__pb2


class SessionManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SignUP = channel.unary_unary(
        '/session_manager.SessionManager/SignUP',
        request_serializer=session__pb2.SignupInput.SerializeToString,
        response_deserializer=session__pb2.SignupOutput.FromString,
        )
    self.Login = channel.unary_unary(
        '/session_manager.SessionManager/Login',
        request_serializer=session__pb2.LoginInput.SerializeToString,
        response_deserializer=session__pb2.LoginOutput.FromString,
        )
    self.Logout = channel.unary_unary(
        '/session_manager.SessionManager/Logout',
        request_serializer=session__pb2.LogoutInput.SerializeToString,
        response_deserializer=session__pb2.LogoutOutput.FromString,
        )
    self.Classify = channel.unary_unary(
        '/session_manager.SessionManager/Classify',
        request_serializer=session__pb2.ClassifyInput.SerializeToString,
        response_deserializer=session__pb2.ClassifyOutput.FromString,
        )


class SessionManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SignUP(self, request, context):
    """Service definitions
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Classify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SessionManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SignUP': grpc.unary_unary_rpc_method_handler(
          servicer.SignUP,
          request_deserializer=session__pb2.SignupInput.FromString,
          response_serializer=session__pb2.SignupOutput.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=session__pb2.LoginInput.FromString,
          response_serializer=session__pb2.LoginOutput.SerializeToString,
      ),
      'Logout': grpc.unary_unary_rpc_method_handler(
          servicer.Logout,
          request_deserializer=session__pb2.LogoutInput.FromString,
          response_serializer=session__pb2.LogoutOutput.SerializeToString,
      ),
      'Classify': grpc.unary_unary_rpc_method_handler(
          servicer.Classify,
          request_deserializer=session__pb2.ClassifyInput.FromString,
          response_serializer=session__pb2.ClassifyOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'session_manager.SessionManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
